---
version: '3.8'

services:
  client:
    stdin_open: true
    command: 'npm run dev'
    tty: true
    build:
      context: apps/client
      target: dev
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - dungeon
    volumes:
      - ./apps/client:/usr/src/app

  server:
    build:
      context: apps/server
      target: dev
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - dungeon
    depends_on:
      - redis
    tty: true
    volumes:
      - ./apps/server:/usr/src/app

  redis:
    image: redis:6.2-alpine
    restart: always
    networks:
      - dungeon
    tty: true
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local

networks:
  dungeon:
    driver: bridge
